### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by inf9144** [AStA-Wedel/Kasse#1]
Database needs a Discount field for sells (receipt)

**Comment by inf9144** [comment]
database need field for article description

**Comment by jwefers** [comment]
added to bill_order (not receipt) as discount INT (representing percent points)

**Comment by MarcusRiemer** [comment]
Just out of interest: How does the approach using percent points handle a changed base price?

**Comment by jwefers** [comment]
Articles are revisioned, if the base price changes, we create a new revision for this particular article. a bill contains a specific revision of an article.

**Comment by inf9144** [comment]
When the Basket is done and gets factured to a bill,
a master discount consisting of all single discounts and the basket discounts is calculated and added to the bill.
The articles themself are versioned.
