### ISSUE TITLE
Eclipse projectfiles are not checked in

### ISSUE THREAD

**Issue by MarcusRiemer** [AStA-Wedel/Kasse#4]
Why are the eclipse projectfiles in .gitignore? I know the actual build is done via Maven, but having project files for eclipse would ease peeking at the source.

**Comment by hastern** [comment]
because most of the time the project files contain user dependend configurations.

**Comment by MarcusRiemer** [comment]
User specific files are stored in the workspace folder, at least the .project and .classpath files use only relative paths and are interchangeable between users.

I have checked in eclipse project files for a while now and never had a problem.

**Comment by alexbiehl** [comment]
Sorry abou that didn't ment do close.

**Comment by alexbiehl** [comment]
We worked by the rule that we never ever check in anything that is generated by maven or the ide. It should be no problem to check it out and convert it to a maven project.

**Comment by MarcusRiemer** [comment]
Ah, the project files are generated. Seems legit.
