### ISSUE TITLE
Best Kasse in the world

### ISSUE THREAD

**Issue by Cikey** [AStA-Wedel/Kasse#7]
:P

**Comment by alexbiehl** [comment]
Willst du ein Revival!?

Christian Kulpa notifications@github.com schrieb am Di., 5. Juli 2016,
17:30:

**Comment by Cikey** [comment]
Es schadet nie die Kasse neu zu entwickeln xD

**Comment by MarcusRiemer** [comment]
Keine AStA-Generation ohne eigene Kasse!
